// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Resolver Driver
//
//  IoTex Resolver Driver
//  Schemes:
//    http
//  Host: 0.0.0.0:8080
//  BasePath: /
//  Version: 1.0.0
//  Contact: <iotex-dev@iotex.io>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
