// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "IoTex Resolver Driver",
    "title": "Resolver Driver",
    "contact": {
      "email": "iotex-dev@iotex.io"
    },
    "version": "1.0.0"
  },
  "host": "0.0.0.0:8080",
  "paths": {
    "/1.0/identifiers/{identifier}": {
      "get": {
        "summary": "Resolve a DID or other identifier.",
        "operationId": "resolve",
        "parameters": [
          {
            "type": "string",
            "description": "A DID or other identifier to be resolved.",
            "name": "identifier",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ResolutionResult"
              }
            }
          },
          "400": {
            "description": "invalid input!"
          },
          "500": {
            "description": "error!"
          }
        }
      }
    }
  },
  "definitions": {
    "ResolutionResult": {
      "description": "The DID resolution result.",
      "type": "object",
      "properties": {
        "didDocument": {
          "type": "object"
        },
        "methodMetadata": {
          "type": "object"
        },
        "resolverMetadata": {
          "type": "object"
        }
      },
      "additionalProperties": false
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "IoTex Resolver Driver",
    "title": "Resolver Driver",
    "contact": {
      "email": "iotex-dev@iotex.io"
    },
    "version": "1.0.0"
  },
  "host": "0.0.0.0:8080",
  "paths": {
    "/1.0/identifiers/{identifier}": {
      "get": {
        "summary": "Resolve a DID or other identifier.",
        "operationId": "resolve",
        "parameters": [
          {
            "type": "string",
            "description": "A DID or other identifier to be resolved.",
            "name": "identifier",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ResolutionResult"
              }
            }
          },
          "400": {
            "description": "invalid input!"
          },
          "500": {
            "description": "error!"
          }
        }
      }
    }
  },
  "definitions": {
    "ResolutionResult": {
      "description": "The DID resolution result.",
      "type": "object",
      "properties": {
        "didDocument": {
          "type": "object"
        },
        "methodMetadata": {
          "type": "object"
        },
        "resolverMetadata": {
          "type": "object"
        }
      },
      "additionalProperties": false
    }
  }
}`))
}
